[theme]
base = "dark"
primaryColor = "#615fff"
backgroundColor = "#1d293d"
secondaryBackgroundColor = "#0f172b"
textColor = "#e2e8f0"
showWidgetBorder = true
borderColor = "#314158"
dataframeHeaderBackgroundColor = "#1d293d"
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
